---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/carlossouza10/Cloud-Project
          searchPaths: config-server-env-repo
server:
  port: 8001
  contextPath: /config-server